plugins:
  - rubocop-rspec

inherit_gem:
  rspec-sleeping_king_studios: config/rubocop-rspec.yml

AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable
  Exclude:
    - gemfiles/*
    - tmp/**/*
    - vendor/**/*

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  AllowedPatterns:
    - '\A\s*#'
  Max: 80

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Style/AccessorGrouping:
  EnforcedStyle: separated

Style/ClassAndModuleChildren:
  Enabled: false
