# frozen_string_literal: true

require 'ephesus/core/formats/plain_text'

module Ephesus::Core::Formats::PlainText
  # Input event generated by a client using the Plain Text format.
  InputMessage =
    Ephesus::Core::Formats::InputMessage.define(:text) do
      def initialize(**)
        format ||= Ephesus::Core::Formats::PlainText.type

        super(format:, text:, **)
      end
    end
end
