# frozen_string_literal: true

require 'ephesus/core/formats/plain_text'

module Ephesus::Core::Formats::PlainText
  # Input event generated by a client using the Plain Text format.
  InputMessage =
    Ephesus::Core::Formats::InputMessage.define(:text) do
      # @param connection [Ephesus::Core::Connection, nil] the connection for the
      #   message.
      # @param format [String] the configured format for the connection.
      # @param text [String] the text to display to the end user.
      def initialize(**)
        format ||= Ephesus::Core::Formats::PlainText.type

        super(format:, text:, **)
      end
    end
end
